# 服务器配置
server:
  # 服务器监听的端口号
  port: 7090
  # Servlet容器配置
  servlet:
    # 应用程序上下文路径
    context-path: /api
    # Session配置
    session:
      # Session超时时间（ISO 8601持续时间格式）
      timeout: PT60M

# Spring框架配置
spring:
  mvc:
    # Favicon相关配置
    favicon:
      # 是否启用favicon图标
      enable: false
    # 控制器映射配置
    throw-exception-if-no-handler-found: true
    # 静态资源映射配置
    resources:
      # 是否自动添加静态资源映射
      add-mappings: false
  # Servlet多部分上传配置
  servlet:
    multipart:
      # 单个文件的最大大小
      max-file-size: 15MB
      # 请求体的最大大小
      max-request-size: 15MB

  # 数据源配置
  datasource:
    # 数据库连接URL
    url: jdbc:mysql://127.0.0.1:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
    # JDBC驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP连接池配置
    hikari:
      # 连接池名称
      pool-name: HikariCPDatasource
      # 最小空闲连接数
      minimum-idle: 5
      # 连接空闲超时时间（毫秒）
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 自动提交事务
      auto-commit: true
      # 连接最大生命周期（毫秒）
      max-lifetime: 1800000
      # 获取连接超时时间（毫秒）
      connection-timeout: 30000
      # 连接验证查询语句
      connection-test-query: SELECT 1

  # 邮件服务配置
  mail:
    # SMTP主机地址
    host: smtp.qq.com
    # SMTP端口号
    port: 465
    # 发送邮件的用户名
    username: 2768158566@qq.com
    # 发送邮件的密码
    password: ihnmjerczfymddei
    # 默认编码
    default-encoding: UTF-8
    # 额外的SMTP属性
    properties:
      mail:
        smtp:
          # SSL套接字工厂类
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          # 调试模式
          debug: true

  # Redis数据库配置
  data:
    redis:
      # 使用的数据库索引
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器端口号
      port: 6379

# 项目配置
project:
  # 项目根目录
  folder: D:\Users\IdeaProjects\easypan

# 日志配置
log:
  root:
    # 根日志级别
    level: debug

# 管理员配置
admin:
  # 管理员邮箱列表
  emails: 邮箱

# 开发环境标志
dev: false

# QQ社交登录配置
qq:
  app:
    # 应用ID
    id: 12333
    # 应用密钥
    key: 2222222
  url:
    # 授权URL
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    # 访问令牌URL
    access-token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    # OpenID获取URL
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    # 用户信息获取URL
    user-info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
    # 回调URL
    redirect: http://easypan.wuhancoder.com/qqlogincallback
